import setuptools

setuptools.setup(name='text-flappy-bird-gym',
      version='0.1.1',
      author='Stergios C.',
      description='Implementation of two OpenAI Gym learning environments of a simple unit-pixel player version of the Flappy Bird.',
      install_requires=['gymnasium==0.29.0', 'numpy'],  # And any other dependencies foo needs
      license="MIT License",
      url="https://gitlab-research.centralesupelec.fr/stergios.christodoulidis/text-flappy-bird-gym",
      packages=setuptools.find_packages(),
      python_requires=">=3.6",
      classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Mathematics",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
)
